-- E-Commerce PL/SQL Logic

-- Function to calculate total price of items in cart
CREATE OR REPLACE FUNCTION Get_Cart_Total(p_user_id IN NUMBER) RETURN NUMBER IS
    v_total NUMBER := 0;
BEGIN
    SELECT SUM(p.price * c.quantity)
    INTO v_total
    FROM Cart c
    JOIN Products p ON c.product_id = p.product_id
    WHERE c.user_id = p_user_id;
    
    RETURN NVL(v_total, 0);
END;
/

-- Procedure to process an order
CREATE OR REPLACE PROCEDURE Process_Order(
    p_user_id IN NUMBER,
    p_status OUT VARCHAR2
) IS
    v_order_id NUMBER;
    v_total NUMBER;
BEGIN
    -- 1. Calculate total
    v_total := Get_Cart_Total(p_user_id);
    
    IF v_total = 0 THEN
        p_status := 'Error: Cart is empty';
        RETURN;
    END IF;

    -- 2. Create Order
    INSERT INTO Orders (user_id, total_amount, status)
    VALUES (p_user_id, v_total, 'Processing')
    RETURNING order_id INTO v_order_id;
    
    -- 3. Move items from Cart to Order_Items and update stock
    FOR r IN (SELECT product_id, quantity FROM Cart WHERE user_id = p_user_id) LOOP
        -- Check stock
        DECLARE
            v_stock NUMBER;
        BEGIN
            SELECT stock_quantity INTO v_stock FROM Products WHERE product_id = r.product_id FOR UPDATE;
            IF v_stock < r.quantity THEN
                RAISE_APPLICATION_ERROR(-20001, 'Insufficient stock for product ID ' || r.product_id);
            END IF;
            
            -- Insert item
            INSERT INTO Order_Items (order_id, product_id, quantity, unit_price)
            SELECT v_order_id, r.product_id, r.quantity, price
            FROM Products WHERE product_id = r.product_id;
            
            -- Update stock
            UPDATE Products 
            SET stock_quantity = stock_quantity - r.quantity
            WHERE product_id = r.product_id;
        END;
    END LOOP;
    
    -- 4. Clear Cart
    DELETE FROM Cart WHERE user_id = p_user_id;
    
    COMMIT;
    p_status := 'Success: Order ' || v_order_id || ' placed';
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        p_status := 'Error: ' || SQLERRM;
END;
/

-- Trigger to log stock updates or alerts (Audit trail example)
CREATE TABLE Stock_Logs (
    log_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id NUMBER,
    old_stock NUMBER,
    new_stock NUMBER,
    change_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE OR REPLACE TRIGGER trg_stock_alert
AFTER UPDATE OF stock_quantity ON Products
FOR EACH ROW
BEGIN
    INSERT INTO Stock_Logs (product_id, old_stock, new_stock)
    VALUES (:OLD.product_id, :OLD.stock_quantity, :NEW.stock_quantity);
END;
/
